<a href="https://colab.research.google.com/github/chaitanyk/pytorch-intro/blob/main/00_pytoruch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print ("Hello !! I am Excited !!");

Hello !! I am Excited !!


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [3]:
scalar = torch.tensor(7)
scalar
scalar.ndim


0

In [4]:
vector = torch.tensor([1,2,3])
vector




tensor([1, 2, 3])

In [5]:
matrix = torch.tensor([[1,2],[3,4]])
matrix


tensor([[1, 2],
        [3, 4]])

In [6]:

tensor = torch.tensor([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
tensor[0][0]
tensor.size()
tensor.ndim



3

In [7]:
rand_tensor = torch.rand(10,2,2,2)
rand_tensor


tensor([[[[0.7791, 0.3595],
          [0.2843, 0.7080]],

         [[0.7302, 0.7185],
          [0.6139, 0.7073]]],


        [[[0.8283, 0.1759],
          [0.5615, 0.0091]],

         [[0.6877, 0.3058],
          [0.3226, 0.8634]]],


        [[[0.6246, 0.7997],
          [0.5170, 0.2572]],

         [[0.7492, 0.7680],
          [0.9151, 0.8245]]],


        [[[0.5416, 0.8832],
          [0.4443, 0.8151]],

         [[0.1435, 0.9841],
          [0.8005, 0.4188]]],


        [[[0.2956, 0.8523],
          [0.7793, 0.8007]],

         [[0.2799, 0.4568],
          [0.2855, 0.9882]]],


        [[[0.4959, 0.2618],
          [0.4122, 0.1435]],

         [[0.3581, 0.9459],
          [0.3512, 0.0930]]],


        [[[0.4246, 0.7411],
          [0.0056, 0.7202]],

         [[0.1422, 0.3243],
          [0.7358, 0.6360]]],


        [[[0.2348, 0.6013],
          [0.1352, 0.7763]],

         [[0.3680, 0.6531],
          [0.1256, 0.7624]]],


        [[[0.0308, 0.1291],
          [0.2143, 0.3568]],

In [8]:
r_image = torch.ones(size=(3,10,10))
r_image


tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.,

In [9]:
data_1=torch.rand(3,10,10)
zero_1=torch.zeros(1,10,10)
zero_1.dtype

torch.float32

In [10]:
r_one = torch.arange(start=0,end=501,step=100)
an_one = torch.ones_like(input=r_one)
an_one

tensor([1, 1, 1, 1, 1, 1])

In [11]:
f_16_ten = torch.tensor([1.2,3.2,4.2],dtype=torch.bfloat16,device=None,requires_grad=False)
f_16_ten.dtype
f_32_tensor = f_16_ten.type(torch.float32)
f_32_tensor.device
print(f"Shape of tensor: {f_32_tensor.shape}")
print(f"Datatype of tensor: {f_32_tensor.dtype}")


Shape of tensor: torch.Size([3])
Datatype of tensor: torch.float32


In [12]:
t1 = torch.tensor([[1,2,3]])
t1a = torch.tensor([1,2,3])
t2 = torch.tensor([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
t3=torch.tensor([[1],[2],[3]])
print(f"t1 size:  {t1.size()}  t1a size:  {t1a.size()} \nt2 size : {t2.size()}  t3 size: {t3.size()}")
print(f"mult t1 t3 : {torch.matmul(t1,t3)}")
print(f"size {t1a.size()} mult t1a: {torch.matmul(t1a,t1a)}")







t1 size:  torch.Size([1, 3])  t1a size:  torch.Size([3]) 
t2 size : torch.Size([3, 4])  t3 size: torch.Size([3, 1])
mult t1 t3 : tensor([[14]])
size torch.Size([3]) mult t1a: 14


In [13]:
t5 = torch.tensor([1,2,3])
torch.matmul(t5,t5)

tensor(14)

In [14]:
left = torch.rand(2,3,4)
right = torch.rand(4,2)
print(f"mul res shape :  {torch.matmul(left,right).shape}");

mul res shape :  torch.Size([2, 3, 2])


In [15]:
x = torch.tensor([3,3,6])
x.type(torch.float32).mean()



tensor(4.)

In [16]:
t1 =  torch.tensor([3,93,6,2,34,65]) # torch.arange(0,100,10)

t1[t1.argmax()]

tensor(93)

In [43]:
x = torch.arange(1.,10.)
x,x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
x_reshape = x.reshape(9,1)
x_reshape.shape
print(f"orig\n {x.shape} \nreshape\n {x_reshape.shape}")
print(f"orig\n {x} \nreshape\n {x_reshape}")

orig torch.Size([9]) 
reshape torch.Size([9, 1])
orig tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) 
reshape tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [47]:
x_re2shape = x_reshape.reshape(1,1,9)
x_re2shape[0][0]
print(f"orig:\n{x_reshape.size()} \nreshape:\n{x_re2shape.size()}")
print(f"orig:\n{x_reshape} \nreshape:\n{x_re2shape}")

orig:
torch.Size([9, 1]) 
reshape:
torch.Size([1, 1, 9])
orig:
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) 
reshape:
tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])


In [48]:
x_reshapeA = x.reshape(3,3)
x_reshapeA


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [39]:
import torch
x = torch.arange(1., 8.)
x, x.shape




(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [42]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [22]:
x=torch.tensor([1,2,3,4])
x_stacked_0 = torch.stack([x,x,x],dim=0)
x_stacked_1 = torch.stack([x,x,x],dim=1)
print(f"x_stacked_0 : {x_stacked_0 } \nx_stacked_1 : {x_stacked_1}")
print(f"{x_stacked_0[1][2]} {x_stacked_1[2][1]}")

x_stacked_0 : tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]) 
x_stacked_1 : tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
3 3


In [23]:
unsq = x_stacked_0.unsqueeze(1)
unsq2 = unsq.unsqueeze(1)
print(f"x_stacked_0: \n{x_stacked_0}\nunsq: \n{unsq}\nunsq2: \n{unsq2}")
sq1=unsq2.squeeze(1)
print(f"sq1 \n{sq1}")

x_stacked_0: 
tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])
unsq: 
tensor([[[1, 2, 3, 4]],

        [[1, 2, 3, 4]],

        [[1, 2, 3, 4]]])
unsq2: 
tensor([[[[1, 2, 3, 4]]],


        [[[1, 2, 3, 4]]],


        [[[1, 2, 3, 4]]]])
sq1 
tensor([[[1, 2, 3, 4]],

        [[1, 2, 3, 4]],

        [[1, 2, 3, 4]]])


In [24]:
x = torch.zeros(2, 1, 2, 1, 2)
#x[0][0][0][0]
print(f"x: \n{x} \nx.squeeze(): \n{x.squeeze()}")
x.squeeze().size()

x: 
tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]]) 
x.squeeze(): 
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


torch.Size([2, 2, 2])

In [25]:
x1 = torch.zeros(3,1,2)
x1

tensor([[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]])

In [26]:
x1 = torch.zeros(2,1,2)
x1_0 = x1.unsqueeze(0)
x1_1 = x1.unsqueeze(3)
print(f"x1:\n {x1} \n{x1.size()} \nunsq 0: \n {x1_0} \n{x1_0.size()}\nunsq 1: \n{x1_1} \n{x1_1.size()}");

x1:
 tensor([[[0., 0.]],

        [[0., 0.]]]) 
torch.Size([2, 1, 2]) 
unsq 0: 
 tensor([[[[0., 0.]],

         [[0., 0.]]]]) 
torch.Size([1, 2, 1, 2])
unsq 1: 
tensor([[[[0.],
          [0.]]],


        [[[0.],
          [0.]]]]) 
torch.Size([2, 1, 2, 1])


In [36]:
x_o = torch.rand(size=(224,224,3))
x_o.size()
x_p = x_o.permute(2,0,1)
x_p.size()
print(f"Original:\n{x_o.size()} \nPermuted: \n{x_p.size()}")
x_v = x_o.view(3,3,3)
print(f"view:\n{x_v.size()}")


Original:
torch.Size([224, 224, 3]) 
Permuted: 
torch.Size([3, 224, 224])


RuntimeError: ignored

In [49]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [50]:
# Add an extra dimension
x_reshaped = x.reshape(1,1,7)
x_reshaped, x_reshaped.shape

(tensor([[[1., 2., 3., 4., 5., 6., 7.]]]), torch.Size([1, 1, 7]))

In [51]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [53]:
 t = torch.rand(4, 4)
 t2=t.view(2,8)
 print(f"Original:\n{t.size()} \nView: \n{t2.size()}")
 print(f"Original:\n{t} \nView: \n{t2}")

Original:
torch.Size([4, 4]) 
View: 
torch.Size([2, 8])
Original:
tensor([[0.8550, 0.6688, 0.6337, 0.2796],
        [0.0729, 0.2694, 0.5803, 0.5820],
        [0.0520, 0.9243, 0.6473, 0.2111],
        [0.5077, 0.5629, 0.7026, 0.7277]]) 
View: 
tensor([[0.8550, 0.6688, 0.6337, 0.2796, 0.0729, 0.2694, 0.5803, 0.5820],
        [0.0520, 0.9243, 0.6473, 0.2111, 0.5077, 0.5629, 0.7026, 0.7277]])


In [59]:
t = torch.rand(2,3,4)
tP=t.permute(0,2,1)
t,t.size(),tP,tP.size()

(tensor([[[0.9529, 0.1553, 0.9317, 0.0205],
          [0.3172, 0.7206, 0.7490, 0.9716],
          [0.7406, 0.9260, 0.2567, 0.3920]],
 
         [[0.1046, 0.6647, 0.9310, 0.7223],
          [0.7650, 0.5050, 0.1572, 0.0839],
          [0.4817, 0.6863, 0.7567, 0.6299]]]),
 torch.Size([2, 3, 4]),
 tensor([[[0.9529, 0.3172, 0.7406],
          [0.1553, 0.7206, 0.9260],
          [0.9317, 0.7490, 0.2567],
          [0.0205, 0.9716, 0.3920]],
 
         [[0.1046, 0.7650, 0.4817],
          [0.6647, 0.5050, 0.6863],
          [0.9310, 0.1572, 0.7567],
          [0.7223, 0.0839, 0.6299]]]),
 torch.Size([2, 4, 3]))

In [91]:
t = torch.arange(1,13).reshape(2,2,3)
t,t[0,:,0]

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [10, 11, 12]]]),
 tensor([1, 4]))

In [93]:
t = torch.arange(1,10).reshape(1,3,3)
t[:,:,2]

tensor([[3, 6, 9]])

## Torch and Numpy

In [102]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
t=torch.from_numpy(array).type(torch.float16)
#ft16=t.type(torch.float16)
#ft16
t1 = torch.ones(7).type(torch.float16)
numpy_t = t1.numpy()
numpy_t


array([1., 1., 1., 1., 1., 1., 1.], dtype=float16)

## Taking random out of random


In [105]:
t1 = torch.rand(3,3,4)
t2 = torch.rand(3,3,4)
t1,t2,t1==t2

(tensor([[[0.6610, 0.8542, 0.0441, 0.6325],
          [0.1530, 0.4544, 0.9613, 0.0074],
          [0.5188, 0.1061, 0.8116, 0.7975]],
 
         [[0.6513, 0.1973, 0.9392, 0.2731],
          [0.4808, 0.2656, 0.5301, 0.7387],
          [0.2592, 0.1327, 0.2589, 0.6766]],
 
         [[0.9748, 0.6938, 0.5063, 0.3089],
          [0.1468, 0.2763, 0.1293, 0.5921],
          [0.7805, 0.0029, 0.1095, 0.8972]]]),
 tensor([[[0.0759, 0.7897, 0.7119, 0.0270],
          [0.3801, 0.1586, 0.7255, 0.8118],
          [0.0836, 0.0983, 0.7379, 0.2308]],
 
         [[0.5372, 0.3245, 0.1895, 0.5128],
          [0.6461, 0.0219, 0.0653, 0.4975],
          [0.4077, 0.5408, 0.4921, 0.5447]],
 
         [[0.9435, 0.6569, 0.1668, 0.9706],
          [0.8142, 0.2420, 0.6534, 0.0309],
          [0.0809, 0.9038, 0.6871, 0.2486]]]),
 tensor([[[False, False, False, False],
          [False, False, False, False],
          [False, False, False, False]],
 
         [[False, False, False, False],
          [False, False, Fa

# With GPU

In [3]:
import torch
#torch.cuda.is_available()
!nvidia-smi


Sat Oct  7 03:56:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [12]:
device = "cuda" if torch.cuda.is_available() else "cpu"
# torch.cuda.device_count()
# device
t1 = torch.tensor([1,2,3])
t1d = t1.to(device);
t2 = t1d.cpu()
t1,t2,t1d



(tensor([1, 2, 3]), tensor([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'))