<a href="https://colab.research.google.com/github/chaitanyk/pytorch-intro/blob/main/00_pytoruch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
print ("Hello !! I am Excited !!");

Hello !! I am Excited !!


In [36]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [37]:
scalar = torch.tensor(7)
scalar
scalar.ndim


0

In [38]:
vector = torch.tensor([1,2,3])
vector




tensor([1, 2, 3])

In [39]:
matrix = torch.tensor([[1,2],[3,4]])
matrix


tensor([[1, 2],
        [3, 4]])

In [40]:

tensor = torch.tensor([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
tensor[0][0]
tensor.size()
tensor.ndim



3

In [41]:
rand_tensor = torch.rand(10,2,2,2)
rand_tensor


tensor([[[[0.8384, 0.0833],
          [0.6567, 0.4919]],

         [[0.1333, 0.7236],
          [0.9095, 0.8385]]],


        [[[0.9841, 0.7471],
          [0.6297, 0.8106]],

         [[0.6989, 0.4053],
          [0.7321, 0.3074]]],


        [[[0.3356, 0.7523],
          [0.5227, 0.6547]],

         [[0.3509, 0.6576],
          [0.0198, 0.6717]]],


        [[[0.0357, 0.7504],
          [0.4356, 0.4244]],

         [[0.8757, 0.9877],
          [0.3962, 0.0936]]],


        [[[0.4277, 0.6043],
          [0.4647, 0.4496]],

         [[0.2454, 0.4273],
          [0.8218, 0.2303]]],


        [[[0.1280, 0.0758],
          [0.3415, 0.0951]],

         [[0.8896, 0.5524],
          [0.4415, 0.0145]]],


        [[[0.9688, 0.0247],
          [0.3266, 0.7848]],

         [[0.1029, 0.2373],
          [0.4995, 0.8767]]],


        [[[0.6743, 0.9747],
          [0.4719, 0.4757]],

         [[0.3221, 0.8696],
          [0.2698, 0.5994]]],


        [[[0.8845, 0.7076],
          [0.8380, 0.7495]],

In [42]:
r_image = torch.ones(size=(3,10,10))
r_image


tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.,

In [43]:
data_1=torch.rand(3,10,10)
zero_1=torch.zeros(1,10,10)
zero_1.dtype

torch.float32

In [44]:
r_one = torch.arange(start=0,end=501,step=100)
an_one = torch.ones_like(input=r_one)
an_one

tensor([1, 1, 1, 1, 1, 1])

In [45]:
f_16_ten = torch.tensor([1.2,3.2,4.2],dtype=torch.bfloat16,device=None,requires_grad=False)
f_16_ten.dtype
f_32_tensor = f_16_ten.type(torch.float32)
f_32_tensor.device
print(f"Shape of tensor: {f_32_tensor.shape}")
print(f"Datatype of tensor: {f_32_tensor.dtype}")


Shape of tensor: torch.Size([3])
Datatype of tensor: torch.float32


In [46]:
t1 = torch.tensor([[1,2,3]])
t1a = torch.tensor([1,2,3])
t2 = torch.tensor([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
t3=torch.tensor([[1],[2],[3]])
print(f"t1 size:  {t1.size()}  t1a size:  {t1a.size()} \nt2 size : {t2.size()}  t3 size: {t3.size()}")
print(f"mult t1 t3 : {torch.matmul(t1,t3)}")
print(f"size {t1a.size()} mult t1a: {torch.matmul(t1a,t1a)}")







t1 size:  torch.Size([1, 3])  t1a size:  torch.Size([3]) 
t2 size : torch.Size([3, 4])  t3 size: torch.Size([3, 1])
mult t1 t3 : tensor([[14]])
size torch.Size([3]) mult t1a: 14


In [47]:
t5 = torch.tensor([1,2,3])
torch.matmul(t5,t5)

tensor(14)

In [48]:
left = torch.rand(2,3,4)
right = torch.rand(4,2)
print(f"mul res shape :  {torch.matmul(left,right).shape}");

mul res shape :  torch.Size([2, 3, 2])


In [49]:
x = torch.tensor([3,3,6])
x.type(torch.float32).mean()



tensor(4.)

In [50]:
t1 =  torch.tensor([3,93,6,2,34,65]) # torch.arange(0,100,10)

t1[t1.argmax()]

tensor(93)

In [51]:
x = torch.arange(1.,10.)
x,x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
x_reshape = x.reshape(9,1)
x_reshape.shape
print(f"orig {x.shape} \nreshape {x_reshape.shape}")

orig torch.Size([9]) 
reshape torch.Size([9, 1])


In [53]:
x_re2shape = x_reshape.reshape(1,1,9)
x_re2shape[0][0]

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
x_reshapeA = x.reshape(3,3)
x_reshapeA


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [59]:
z=x.view(1,9)
z[0][0] = 3
x



tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.])