<a href="https://colab.research.google.com/github/chaitanyk/pytorch-intro/blob/main/fund_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
t = torch.tensor([[[[1]]]])
t.item()

1

In [38]:

t = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = t.pow(2).sum()
out.backward()
t.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [42]:
t = torch.tensor([[1,2],[3,4],[5,6]])
t.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [45]:
t,t.T,t.H

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[1, 3, 5],
         [2, 4, 6]]))

In [57]:
t = torch.tensor([[[[1,2],[4,3],[5,6]],[[1,2],[3,4],[5,6]]]])
t,t.mT

(tensor([[[[1, 2],
           [4, 3],
           [5, 6]],
 
          [[1, 2],
           [3, 4],
           [5, 6]]]]),
 tensor([[[[1, 4, 5],
           [2, 3, 6]],
 
          [[1, 3, 5],
           [2, 4, 6]]]]))

In [15]:
import torch

RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)
t=torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
t2=torch.rand(1,7)
t3=t.matmul(t2.T)
t,t2,t3

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]))

In [3]:
import torch
RANDOM_SEED=1234
torch.cuda.manual_seed(RANDOM_SEED)
t=torch.rand(7,7,device="cuda")
t


tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
        [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
        [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
        [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
        [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
        [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
        [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
       device='cuda:0')

In [5]:
torch.manual_seed(1234)
r1=torch.rand(2,3).to("cuda")
torch.manual_seed(1234)
r2=torch.rand(2,3).to("cuda")
r1,r2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [10]:
torch.manual_seed(1234)
r1=torch.rand(2,3).to("cuda")
torch.manual_seed(1234)
r2=torch.rand(2,3).to("cuda")
res=r1.matmul(r2.T)
# r1.size(), r2.size(),res.size()
# res.argmin(),res.argmax(),res,res.min(),res.max()

(tensor(1, device='cuda:0'),
 tensor(3, device='cuda:0'),
 tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'),
 tensor(0.2161, device='cuda:0'),
 tensor(0.6287, device='cuda:0'))

In [17]:

# Set seed
SEED=7
torch.manual_seed(SEED)
t1=torch.rand(1,1,1,10)
t2=t1.squeeze()
t2.size(),t1,t2


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes

(torch.Size([10]),
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))